name: proyecto_157101
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.0
  - requests=2.32.3
  - jupyterlab=4.0.0
  - ipython=9.2.0
  - ipykernel=6.29.5
  - beautifulsoup4=4.12.3
  - tqdm=4.67.1
  - python-dotenv=1.0.1